name: Generate, Sign, and Commit SBOM

on:
  push:
    branches:
      - main

jobs:
  generate-and-sign-sbom:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      
      - name: Generate SBOM in CycloneDX format
        run: syft . -o cyclonedx-json=log4shell-vulnerable-app-CDX.json
      
      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: SBOM
          path: log4shell-vulnerable-app-CDX.json
      
      - name: Install Cosign
        run: |
          COSIGN_VERSION="v1.5.2"
          wget https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64 -O cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/
      
      - name: Sign the SBOM
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: cosign sign-blob --oidc-issuer=https://token.actions.githubusercontent.com --output-signature log4shell-vulnerable-app-CDX.json.sig log4shell-vulnerable-app-CDX.json
      
      - name: Commit SBOM and Signature to repository
        run: |
          git config --local user.email "<your_email@example.com>"
          git config --local user.name "<Your GitHub Username>"
          git add log4shell-vulnerable-app-CDX.json log4shell-vulnerable-app-CDX.json.sig
          git commit -m "Add and Sign SBOM for log4shell-vulnerable-app"
          git push

  vulnerability-analysis:
    needs: generate-and-sign-sbom
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Download SBOM artifact
        uses: actions/download-artifact@v2
        with:
          name: SBOM
      
      - name: Install Grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      
      - name: Run vulnerability analysis
        run: grype sbom:log4shell-vulnerable-app-CDX.json -o table | tail -n +2 | awk 'BEGIN {OFS=FS="\t"} { if($6=="Critical") $6="1Critical"; else if($6=="High") $6="2High"; else if($6=="Medium") $6="3Medium"; else if($6=="Low") $6="4Low"; print $0; }' | sort -k6,6 -k1,1d | awk '{sub(/^[1-4]/, "", $6); print}'
