name: Generate SBOM in CDX json and VA

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM in CycloneDX format
        #run: syft ./src/main/ -o cyclonedx-json=log4shell-vulnerable-app-CDX.json
        run: syft . -o cyclonedx-json=log4shell-vulnerable-app-CDX.json
        #working-directory: log4shell-vulnerable-app/src/main/
        
      - name: Generate SBOM in console
        run: syft .
        
      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: SBOM
          path: log4shell-vulnerable-app-CDX.json
      
      - name: Commit SBOM to repository
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add log4shell-vulnerable-app-CDX.json
          git commit -m "Add SBOM for log4shell-vulnerable-app"
          git push

  vulnerability-analysis:
    needs: generate-sbom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download SBOM artifact
        uses: actions/download-artifact@v2
        with:
          name: SBOM

      - name: Install Grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run vulnerability analysis
        #run: grype sbom:log4shell-vulnerable-app-CDX.json -o table
        run: grype sbom:log4shell-vulnerable-app-CDX.json -o table | tail -n +2 | awk 'BEGIN {OFS=FS="\t"} { if($6=="Critical") $6="1Critical"; else if($6=="High") $6="2High"; else if($6=="Medium") $6="3Medium"; else if($6=="Low") $6="4Low"; print $0; }' | sort -k6,6 -k1,1d | awk '{sub(/^[1-4]/, "", $6); print}'

name: Sign SBOM with Cosign

on:
  push:
    paths:
      - 'log4shell-vulnerable-app-CDX.json'

jobs:
  sign-and-commit-sbom:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cosign
        run: |
          COSIGN_VERSION="v1.5.2"
          wget https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64 -O cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/
      - name: List files in the current directory
        run: ls -l

      - name: Sign the SBOM
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: cosign sign-blob --oidc-issuer=https://token.actions.githubusercontent.com --output-signature log4shell-vulnerable-app-CDX.json.sig log4shell-vulnerable-app-CDX.json

      - name: Commit Signature
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "Your GitHub Username"
          git add log4shell-vulnerable-app-CDX.json.sig
          git commit -m "Sign SBOM with Cosign"
          git push
