name: Sign SBOM with Cosign

on:
  push:
    paths:
      - 'log4shell-vulnerable-app-CDX.json'

jobs:
  sign-and-commit-sbom:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cosign
        run: |
          COSIGN_VERSION="v1.5.2"
          wget https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64 -O cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/
      - name: List files in the current directory
        run: ls -l

      - name: Sign the SBOM
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: cosign sign-blob --oidc-issuer=https://token.actions.githubusercontent.com --output-signature log4shell-vulnerable-app-CDX.json.sig log4shell-vulnerable-app-CDX.json

      - name: Commit Signature
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "Your GitHub Username"
          git add log4shell-vulnerable-app-CDX.json.sig
          git commit -m "Sign SBOM with Cosign"
          git push
#test
